name = "Spider"
uuid = "dae5e5ee-8eca-4ada-95ce-87810a1e1f9e"
authors = ["Miles Stoudenmire <miles.stoudenmire@gmail.com>"]
version = "0.1.0"

[deps]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"

[compat]
CommonMark = "0.5"
